const countrylabels = [
    {
      label: 'Afghanistan (+93)',
      text: '+93',
      value: 'AF',
      latitude: 33,
      longitude: 65,
      key: '+93',
    },
    {
      label: 'Albania (+355)',
      text: '+355',
      value: 'AL',
      latitude: 41,
      longitude: 20,
      key: '+355',
    },
    {
      label: 'Algeria (+213)',
      text: '+213',
      value: 'DZ',
      latitude: 28,
      longitude: 3,
      key: '+213',
    },
    {
      label: 'Andorra (+376)',
      text: '+376',
      value: 'AD',
      latitude: 42.5,
      longitude: 1.6,
      key: '+376',
    },
    {
      label: 'Angola (+244)',
      text: '+244',
      value: 'AO',
      latitude: -12.5,
      longitude: 18.5,
      key: '+244',
    },
    {
      label: 'Anguilla (+1 264)',
      text: '+1 264',
      value: 'AI',
      latitude: 18.25,
      longitude: -63.1667,
      key: '+1 264',
    },
    {
      label: 'Antarctica (+672)',
      text: '+672',
      value: 'AQ',
      latitude: -90,
      longitude: '0',
      key: '+672',
    },
    {
      label: 'Antigua and Barbuda (+1268)',
      text: '+1268',
      value: 'AG',
      latitude: 17.05,
      longitude: -61.8,
      key: '+1268',
    },
    {
      label: 'Argentina (+54)',
      text: '+54',
      value: 'AR',
      latitude: -34,
      longitude: -64,
      key: '+54',
    },
    {
      label: 'Armenia (+374)',
      text: '+374',
      value: 'AM',
      latitude: 40,
      longitude: 45,
      key: '+374',
    },
    {
      label: 'Aruba (+297)',
      text: '+297',
      value: 'AW',
      latitude: 12.5,
      longitude: -69.9667,
      key: '+297',
    },
    {
      label: 'Australia (+61)',
      text: '+61',
      value: 'AU',
      latitude: -27,
      longitude: 133,
      key: '+61',
    },
    {
      label: 'Austria (+43)',
      text: '+43',
      value: 'AT',
      latitude: 47.3333,
      longitude: 13.3333,
      key: '+43',
    },
    {
      label: 'Azerbaijan (+994)',
      text: '+994',
      value: 'AZ',
      latitude: 40.5,
      longitude: 47.5,
      key: '+994',
    },
    {
      label: 'Bahamas (+1 242)',
      text: '+1 242',
      value: 'BS',
      latitude: 24.25,
      longitude: -76,
      key: '+1 242',
    },
    {
      label: 'Bahrain (+973)',
      text: '+973',
      value: 'BH',
      latitude: 26,
      longitude: 50.55,
      key: '+973',
    },
    {
      label: 'Bangladesh (+880)',
      text: '+880',
      value: 'BD',
      latitude: 24,
      longitude: 90,
      key: '+880',
    },
    {
      label: 'Barbados (+1 246)',
      text: '+1 246',
      value: 'BB',
      latitude: 13.1667,
      longitude: -59.5333,
      key: '+1 246',
    },
    {
      label: 'Belarus (+375)',
      text: '+375',
      value: 'BY',
      latitude: 53,
      longitude: 28,
      key: '+375',
    },
    {
      label: 'Belgium (+32)',
      text: '+32',
      value: 'BE',
      latitude: 50.8333,
      longitude: 4,
      key: '+32',
    },
    {
      label: 'Belize (+501)',
      text: '+501',
      value: 'BZ',
      latitude: 17.25,
      longitude: -88.75,
      key: '+501',
    },
    {
      label: 'Benin (+229)',
      text: '+229',
      value: 'BJ',
      latitude: 9.5,
      longitude: 2.25,
      key: '+229',
    },
    {
      label: 'Bermuda (+1 441)',
      text: '+1 441',
      value: 'BM',
      latitude: 32.3333,
      longitude: -64.75,
      key: '+1 441',
    },
    {
      label: 'Bhutan (+975)',
      text: '+975',
      value: 'BT',
      latitude: 27.5,
      longitude: 90.5,
      key: '+975',
    },
    {
      label: 'Bolivia, Plurinational State of Bolivia (+591)',
      text: '+591',
      value: 'BO',
      latitude: -17,
      longitude: -65,
      key: '+591',
    },
    {
      label: 'Bosnia and Herzegovina (+387)',
      text: '+387',
      value: 'BA',
      latitude: 44,
      longitude: 18,
      key: '+387',
    },
    {
      label: 'Botswana (+267)',
      text: '+267',
      value: 'BW',
      latitude: -22,
      longitude: 24,
      key: '+267',
    },
    {
      label: 'Bouvet Island (+55)',
      text: '+55',
      value: 'BV',
      latitude: -54.4333,
      longitude: 3.4,
      key: '+55',
    },
    {
      label: 'Brazil (+55)',
      text: '+55',
      value: 'BR',
      latitude: -10,
      longitude: -55,
      key: '+55',
    },
    {
      label: 'British Indian Ocean Territory (+246)',
      text: '+246',
      value: 'IO',
      latitude: -6,
      longitude: 71.5,
      key: '+246',
    },
    {
      label: 'Brunei Darussalam (+673)',
      text: '+673',
      value: 'BN',
      latitude: 4.5,
      longitude: 114.6667,
      key: '+673',
    },
    {
      label: 'Bulgaria (+359)',
      text: '+359',
      value: 'BG',
      latitude: 43,
      longitude: 25,
      key: '+359',
    },
    {
      label: 'Burkina Faso (+226)',
      text: '+226',
      value: 'BF',
      latitude: 13,
      longitude: -2,
      key: '+226',
    },
    {
      label: 'Burundi (+257)',
      text: '+257',
      value: 'BI',
      latitude: -3.5,
      longitude: 30,
      key: '+257',
    },
    {
      label: 'Cambodia (+855)',
      text: '+855',
      value: 'KH',
      latitude: 13,
      longitude: 105,
      key: '+855',
    },
    {
      label: 'Cameroon (+237)',
      text: '+237',
      value: 'CM',
      latitude: 6,
      longitude: 12,
      key: '+237',
    },
    {
      label: 'Canada (+1)',
      text: '+1',
      value: 'CA',
      latitude: 60,
      longitude: -95,
      key: '+1',
    },
    {
      label: 'Cape Verde (+238)',
      text: '+238',
      value: 'CV',
      latitude: 16,
      longitude: -24,
      key: '+238',
    },
    {
      label: 'Cayman Islands (+1345)',
      text: '+1345',
      value: 'KY',
      latitude: 19.5,
      longitude: -80.5,
      key: '+1345',
    },
    {
      label: 'Central African Republic (+236)',
      text: '+236',
      value: 'CF',
      latitude: 7,
      longitude: 21,
      key: '+236',
    },
    {
      label: 'Chad (+235)',
      text: '+235',
      value: 'TD',
      latitude: 15,
      longitude: 19,
      key: '+235',
    },
    {
      label: 'Chile (+56)',
      text: '+56',
      value: 'CL',
      latitude: -30,
      longitude: -71,
      key: '+56',
    },
    {
      label: 'China (+86)',
      text: '+86',
      value: 'CN',
      latitude: 35,
      longitude: 105,
      key: '+86',
    },
    {
      label: 'Christmas Island (+61)',
      text: '+61',
      value: 'CX',
      latitude: -10.5,
      longitude: 105.6667,
      key: '+61',
    },
    {
      label: 'Cocos (Keeling) Islands (+61)',
      text: '+61',
      value: 'CC',
      latitude: -12.5,
      longitude: 96.8333,
      key: '+61',
    },
    {
      label: 'Colombia (+57)',
      text: '+57',
      value: 'CO',
      latitude: 4,
      longitude: -72,
      key: '+57',
    },
    {
      label: 'Comoros (+269)',
      text: '+269',
      value: 'KM',
      latitude: -12.1667,
      longitude: 44.25,
      key: '+269',
    },
    {
      label: 'Congo (+242)',
      text: '+242',
      value: 'CG',
      latitude: -1,
      longitude: 15,
      key: '+242',
    },
    {
      label: 'Congo, The Democratic Republic of the (+243)',
      text: '+243',
      value: 'CD',
      latitude: '0',
      longitude: 25,
      key: '+243',
    },
    {
      label: 'Cook Islands (+682)',
      text: '+682',
      value: 'CK',
      latitude: -21.2333,
      longitude: -159.7667,
      key: '+682',
    },
    {
      label: 'Costa Rica (+506)',
      text: '+506',
      value: 'CR',
      latitude: 10,
      longitude: -84,
      key: '+506',
    },
    {
      label: "Cote d'Ivoire (+225)",
      value: '+225',
      latitude: 8,
      longitude: -5,
    },
    {
      label: 'Croatia (+385)',
      text: '+385',
      value: 'HR',
      latitude: 45.1667,
      longitude: 15.5,
      key: '+385',
    },
    {
      label: 'Cuba (+53)',
      text: '+53',
      value: 'CU',
      latitude: 21.5,
      longitude: -80,
      key: '+53',
    },
    {
      label: 'Cyprus (+357)',
      text: '+357',
      value: 'CY',
      latitude: 35,
      longitude: 33,
      key: '+357',
    },
    {
      label: 'Czech Republic (+420)',
      text: '+420',
      value: 'CZ',
      latitude: 49.75,
      longitude: 15.5,
      key: '+420',
    },
    {
      label: 'Denmark (+45)',
      text: '+45',
      value: 'DK',
      latitude: 56,
      longitude: 10,
      key: '+45',
    },
    {
      label: 'Djibouti (+253)',
      text: '+253',
      value: 'DJ',
      latitude: 11.5,
      longitude: 43,
      key: '+253',
    },
    {
      label: 'Dominica (+1 767)',
      text: '+1 767',
      value: 'DM',
      latitude: 15.4167,
      longitude: -61.3333,
      key: '+1 767',
    },
    {
      label: 'Dominican Republic (+1 849)',
      text: '+1 849',
      value: 'DO',
      latitude: 19,
      longitude: -70.6667,
      key: '+1 849',
    },
    {
      label: 'Ecuador (+593)',
      text: '+593',
      value: 'EC',
      latitude: -2,
      longitude: -77.5,
      key: '+593',
    },
    {
      label: 'Egypt (+20)',
      text: '+20',
      value: 'EG',
      latitude: 27,
      longitude: 30,
      key: '+20',
    },
    {
      label: 'El Salvador (+503)',
      text: '+503',
      value: 'SV',
      latitude: 13.8333,
      longitude: -88.9167,
      key: '+503',
    },
    {
      label: 'Equatorial Guinea (+240)',
      text: '+240',
      value: 'GQ',
      latitude: 2,
      longitude: 10,
      key: '+240',
    },
    {
      label: 'Eritrea (+291)',
      text: '+291',
      value: 'ER',
      latitude: 15,
      longitude: 39,
      key: '+291',
    },
    {
      label: 'Estonia (+372)',
      text: '+372',
      value: 'EE',
      latitude: 59,
      longitude: 26,
      key: '+372',
    },
    {
      label: 'Ethiopia (+251)',
      text: '+251',
      value: 'ET',
      latitude: 8,
      longitude: 38,
      key: '+251',
    },
    {
      label: 'Falkland Islands (Malvinas) (+500)',
      text: '+500',
      value: 'FK',
      latitude: -51.75,
      longitude: -59,
      key: '+500',
    },
    {
      label: 'Faroe Islands (+298)',
      text: '+298',
      value: 'FO',
      latitude: 62,
      longitude: -7,
      key: '+298',
    },
    {
      label: 'Fiji (+679)',
      text: '+679',
      value: 'FJ',
      latitude: -18,
      longitude: 175,
      key: '+679',
    },
    {
      label: 'Finland (+358)',
      text: '+358',
      value: 'FI',
      latitude: 64,
      longitude: 26,
      key: '+358',
    },
    {
      label: 'France (+33)',
      text: '+33',
      value: 'FR',
      latitude: 46,
      longitude: 2,
      key: '+33',
    },
    {
      label: 'French Guiana (+594)',
      text: '+594',
      value: 'GF',
      latitude: 4,
      longitude: -53,
      key: '+594',
    },
    {
      label: 'French Polynesia (+689)',
      text: '+689',
      value: 'PF',
      latitude: -15,
      longitude: -140,
      key: '+689',
    },
    {
      label: 'French Southern and Antarctic Lands (+262)',
      text: '+262',
      value: 'TF',
      latitude: -43,
      longitude: 67,
      key: '+262',
    },
    {
      label: 'Gabon (+241)',
      text: '+241',
      value: 'GA',
      latitude: -1,
      longitude: 11.75,
      key: '+241',
    },
    {
      label: 'Gambia (+220)',
      text: '+220',
      value: 'GM',
      latitude: 13.4667,
      longitude: -16.5667,
      key: '+220',
    },
    {
      label: 'Georgia (+995)',
      text: '+995',
      value: 'GE',
      latitude: 42,
      longitude: 43.5,
      key: '+995',
    },
    {
      label: 'Germany (+49)',
      text: '+49',
      value: 'DE',
      latitude: 51,
      longitude: 9,
      key: '+49',
    },
    {
      label: 'Ghana (+233)',
      text: '+233',
      value: 'GH',
      latitude: 8,
      longitude: -2,
      key: '+233',
    },
    {
      label: 'Gibraltar (+350)',
      text: '+350',
      value: 'GI',
      latitude: 36.1833,
      longitude: -5.3667,
      key: '+350',
    },
    {
      label: 'Greece (+30)',
      text: '+30',
      value: 'GR',
      latitude: 39,
      longitude: 22,
      key: '+30',
    },
    {
      label: 'Greenland (+299)',
      text: '+299',
      value: 'GL',
      latitude: 72,
      longitude: -40,
      key: '+299',
    },
    {
      label: 'Grenada (+1 473)',
      text: '+1 473',
      value: 'GD',
      latitude: 12.1167,
      longitude: -61.6667,
      key: '+1 473',
    },
    {
      label: 'Guadeloupe (+590)',
      text: '+590',
      value: 'GP',
      latitude: 16.25,
      longitude: -61.5833,
      key: '+590',
    },
    {
      label: 'Guam (+1 671)',
      text: '+1 671',
      value: 'GU',
      latitude: 13.4667,
      longitude: 144.7833,
      key: '+1 671',
    },
    {
      label: 'Guatemala (+502)',
      text: '+502',
      value: 'GT',
      latitude: 15.5,
      longitude: -90.25,
      key: '+502',
    },
    {
      label: 'Guernsey (+44)',
      text: '+44',
      value: 'GG',
      latitude: 49.5,
      longitude: -2.56,
      key: '+44',
    },
    {
      label: 'Guinea (+224)',
      text: '+224',
      value: 'GN',
      latitude: 11,
      longitude: -10,
      key: '+224',
    },
    {
      label: 'Guinea-Bissau (+245)',
      text: '+245',
      value: 'GW',
      latitude: 12,
      longitude: -15,
      key: '+245',
    },
    {
      label: 'Guyana (+592)',
      text: '+592',
      value: 'GY',
      latitude: 5,
      longitude: -59,
      key: '+592',
    },
    {
      label: 'Haiti (+509)',
      text: '+509',
      value: 'HT',
      latitude: 19,
      longitude: -72.4167,
      key: '+509',
    },
    {
      label: 'Heard Island and McDonald Islands (+672)',
      text: '+672',
      value: 'HM',
      latitude: -53.1,
      longitude: 72.5167,
      key: '+672',
    },
    {
      label: 'Holy See (Vatican City State) (+379)',
      text: '+379',
      value: 'VA',
      latitude: 41.9,
      longitude: 12.45,
      key: '+379',
    },
    {
      label: 'Honduras (+504)',
      text: '+504',
      value: 'HN',
      latitude: 15,
      longitude: -86.5,
      key: '+504',
    },
    {
      label: 'Hong Kong (+852)',
      text: '+852',
      value: 'HK',
      latitude: 22.25,
      longitude: 114.1667,
      key: '+852',
    },
    {
      label: 'Hungary (+36)',
      text: '+36',
      value: 'HU',
      latitude: 47,
      longitude: 20,
      key: '+36',
    },
    {
      label: 'Iceland (+354)',
      text: '+354',
      value: 'IS',
      latitude: 65,
      longitude: -18,
      key: '+354',
    },
    {
      label: 'India (+91)',
      text: '+91',
      value: 'IN',
      latitude: 20,
      longitude: 77,
      key: '+91',
    },
    {
      label: 'Indonesia (+62)',
      text: '+62',
      value: 'ID',
      latitude: -5,
      longitude: 120,
      key: '+62',
    },
    {
      label: 'Iran, Islamic Republic of (+98)',
      text: '+98',
      value: 'IR',
      latitude: 32,
      longitude: 53,
      key: '+98',
    },
    {
      label: 'Iraq (+964)',
      text: '+964',
      value: 'IQ',
      latitude: 33,
      longitude: 44,
      key: '+964',
    },
    {
      label: 'Ireland (+353)',
      text: '+353',
      value: 'IE',
      latitude: 53,
      longitude: -8,
      key: '+353',
    },
    {
      label: 'Isle of Man (+44)',
      text: '+44',
      value: 'IM',
      latitude: 54.23,
      longitude: -4.55,
      key: '+44',
    },
    {
      label: 'Israel (+972)',
      text: '+972',
      value: 'IL',
      latitude: 31.5,
      longitude: 34.75,
      key: '+972',
    },
    {
      label: 'Italy (+39)',
      text: '+39',
      value: 'IT',
      latitude: 42.8333,
      longitude: 12.8333,
      key: '+39',
    },
    {
      label: 'Jamaica (+1 876)',
      text: '+1 876',
      value: 'JM',
      latitude: 18.25,
      longitude: -77.5,
      key: '+1 876',
    },
    {
      label: 'Japan (+81)',
      text: '+81',
      value: 'JP',
      latitude: 36,
      longitude: 138,
      key: '+81',
    },
    {
      label: 'Jersey (+44)',
      text: '+44',
      value: 'JE',
      latitude: 49.21,
      longitude: -2.13,
      key: '+44',
    },
    {
      label: 'Jordan (+962)',
      text: '+962',
      value: 'JO',
      latitude: 31,
      longitude: 36,
      key: '+962',
    },
    {
      label: 'Kazakhstan (+7)',
      text: '+7',
      value: 'KZ',
      latitude: 48,
      longitude: 68,
      key: '+7',
    },
    {
      label: 'Kenya (+254)',
      text: '+254',
      value: 'KE',
      latitude: 1,
      longitude: 38,
      key: '+254',
    },
    {
      label: 'Kiribati (+686)',
      text: '+686',
      value: 'KI',
      latitude: 1.4167,
      longitude: 173,
      key: '+686',
    },
    {
      label: "Korea, Democratic People's Republic of (+850)",
      value: '+850',
      latitude: 40,
      longitude: 127,
    },
    {
      label: 'Korea, Republic of (+82)',
      text: '+82',
      value: 'KR',
      latitude: 37,
      longitude: 127.5,
      key: '+82',
    },
    {
      label: 'Kuwait (+965)',
      text: '+965',
      value: 'KW',
      latitude: 29.3375,
      longitude: 47.6581,
      key: '+965',
    },
    {
      label: 'Kyrgyzstan (+996)',
      text: '+996',
      value: 'KG',
      latitude: 41,
      longitude: 75,
      key: '+996',
    },
    {
      label: "Lao People's Democratic Republic (+856)",
      text: '+856',
      value: 'LA',
      latitude: 18,
      longitude: 105,
      key: '+856',
    },
    {
      label: 'Latvia (+371)',
      text: '+371',
      value: 'LV',
      latitude: 57,
      longitude: 25,
      key: '+371',
    },
    {
      label: 'Lebanon (+961)',
      text: '+961',
      value: 'LB',
      latitude: 33.8333,
      longitude: 35.8333,
      key: '+961',
    },
    {
      label: 'Lesotho (+266)',
      text: '+266',
      value: 'LS',
      latitude: -29.5,
      longitude: 28.5,
      key: '+266',
    },
    {
      label: 'Liberia (+231)',
      text: '+231',
      value: 'LR',
      latitude: 6.5,
      longitude: -9.5,
      key: '+231',
    },
    {
      label: 'Libyan Arab Jamahiriya (+218)',
      text: '+218',
      value: 'LY',
      latitude: 25,
      longitude: 17,
      key: '+218',
    },
    {
      label: 'Liechtenstein (+423)',
      text: '+423',
      value: 'LI',
      latitude: 47.1667,
      longitude: 9.5333,
      key: '+423',
    },
    {
      label: 'Lithuania (+370)',
      text: '+370',
      value: 'LT',
      latitude: 56,
      longitude: 24,
      key: '+370',
    },
    {
      label: 'Luxembourg (+352)',
      text: '+352',
      value: 'LU',
      latitude: 49.75,
      longitude: 6.1667,
      key: '+352',
    },
    {
      label: 'Macao (+853)',
      text: '+853',
      value: 'MO',
      latitude: 22.1667,
      longitude: 113.55,
      key: '+853',
    },
    {
      label: 'Macedonia, The Former Yugoslav Republic of (+389)',
      text: '+389',
      value: 'MK',
      latitude: 41.8333,
      longitude: 22,
      key: '+389',
    },
    {
      label: 'Madagascar (+261)',
      text: '+261',
      value: 'MG',
      latitude: -20,
      longitude: 47,
      key: '+261',
    },
    {
      label: 'Malawi (+265)',
      text: '+265',
      value: 'MW',
      latitude: -13.5,
      longitude: 34,
      key: '+265',
    },
    {
      label: 'Malaysia (+60)',
      text: '+60',
      value: 'MY',
      latitude: 2.5,
      longitude: 112.5,
      key: '+60',
    },
    {
      label: 'Maldives (+960)',
      text: '+960',
      value: 'MV',
      latitude: 3.25,
      longitude: 73,
      key: '+960',
    },
    {
      label: 'Mali (+223)',
      text: '+223',
      value: 'ML',
      latitude: 17,
      longitude: -4,
      key: '+223',
    },
    {
      label: 'Malta (+356)',
      text: '+356',
      value: 'MT',
      latitude: 35.8333,
      longitude: 14.5833,
      key: '+356',
    },
    {
      label: 'Marshall Islands (+692)',
      text: '+692',
      value: 'MH',
      latitude: 9,
      longitude: 168,
      key: '+692',
    },
    {
      label: 'Martinique (+596)',
      text: '+596',
      value: 'MQ',
      latitude: 14.6667,
      longitude: -61,
      key: '+596',
    },
    {
      label: 'Mauritania (+222)',
      text: '+222',
      value: 'MR',
      latitude: 20,
      longitude: -12,
      key: '+222',
    },
    {
      label: 'Mauritius (+230)',
      text: '+230',
      value: 'MU',
      latitude: -20.2833,
      longitude: 57.55,
      key: '+230',
    },
    {
      label: 'Mayotte (+262)',
      text: '+262',
      value: 'YT',
      latitude: -12.8333,
      longitude: 45.1667,
      key: '+262',
    },
    {
      label: 'Mexico (+52)',
      text: '+52',
      value: 'MX',
      latitude: 23,
      longitude: -102,
      key: '+52',
    },
    {
      label: 'Micronesia, Federated States of (+691)',
      text: '+691',
      value: 'FM',
      latitude: 6.9167,
      longitude: 158.25,
      key: '+691',
    },
    {
      label: 'Moldova, Republic of (+373)',
      text: '+373',
      value: 'MD',
      latitude: 47,
      longitude: 29,
      key: '+373',
    },
    {
      label: 'Monaco (+377)',
      text: '+377',
      value: 'MC',
      latitude: 43.7333,
      longitude: 7.4,
      key: '+377',
    },
    {
      label: 'Mongolia (+976)',
      text: '+976',
      value: 'MN',
      latitude: 46,
      longitude: 105,
      key: '+976',
    },
    {
      label: 'Montenegro (+382)',
      text: '+382',
      value: 'ME',
      latitude: 42,
      longitude: 19,
      key: '+382',
    },
    {
      label: 'Montserrat (+1664)',
      text: '+1664',
      value: 'MS',
      latitude: 16.75,
      longitude: -62.2,
      key: '+1664',
    },
    {
      label: 'Morocco (+212)',
      text: '+212',
      value: 'MA',
      latitude: 32,
      longitude: -5,
      key: '+212',
    },
    {
      label: 'Mozambique (+258)',
      text: '+258',
      value: 'MZ',
      latitude: -18.25,
      longitude: 35,
      key: '+258',
    },
    {
      label: 'Myanmar (+95)',
      text: '+95',
      value: 'MM',
      latitude: 22,
      longitude: 98,
      key: '+95',
    },
    {
      label: 'Namibia (+264)',
      text: '+264',
      value: 'NA',
      latitude: -22,
      longitude: 17,
      key: '+264',
    },
    {
      label: 'Nauru (+674)',
      text: '+674',
      value: 'NR',
      latitude: -0.5333,
      longitude: 166.9167,
      key: '+674',
    },
    {
      label: 'Nepal (+977)',
      text: '+977',
      value: 'NP',
      latitude: 28,
      longitude: 84,
      key: '+977',
    },
    {
      label: 'Netherlands (+31)',
      text: '+31',
      value: 'NL',
      latitude: 52.5,
      longitude: 5.75,
      key: '+31',
    },
    {
      label: 'Netherlands Antilles (+599)',
      text: '+599',
      value: 'AN',
      latitude: 12.25,
      longitude: -68.75,
      key: '+599',
    },
    {
      label: 'New Caledonia (+687)',
      text: '+687',
      value: 'NC',
      latitude: -21.5,
      longitude: 165.5,
      key: '+687',
    },
    {
      label: 'New Zealand (+64)',
      text: '+64',
      value: 'NZ',
      latitude: -41,
      longitude: 174,
      key: '+64',
    },
    {
      label: 'Nicaragua (+505)',
      text: '+505',
      value: 'NI',
      latitude: 13,
      longitude: -85,
      key: '+505',
    },
    {
      label: 'Niger (+227)',
      text: '+227',
      value: 'NE',
      latitude: 16,
      longitude: 8,
      key: '+227',
    },
    {
      label: 'Nigeria (+234)',
      text: '+234',
      value: 'NG',
      latitude: 10,
      longitude: 8,
      key: '+234',
    },
    {
      label: 'Niue (+683)',
      text: '+683',
      value: 'NU',
      latitude: -19.0333,
      longitude: -169.8667,
      key: '+683',
    },
    {
      label: 'Norfolk Island (+672)',
      text: '+672',
      value: 'NF',
      latitude: -29.0333,
      longitude: 167.95,
      key: '+672',
    },
    {
      label: 'Northern Mariana Islands (+1 670)',
      text: '+1 670',
      value: 'MP',
      latitude: 15.2,
      longitude: 145.75,
      key: '+1 670',
    },
    {
      label: 'Norway (+47)',
      text: '+47',
      value: 'NO',
      latitude: 62,
      longitude: 10,
      key: '+47',
    },
    {
      label: 'Oman (+968)',
      text: '+968',
      value: 'OM',
      latitude: 21,
      longitude: 57,
      key: '+968',
    },
    {
      label: 'Pakistan (+92)',
      text: '+92',
      value: 'PK',
      latitude: 30,
      longitude: 70,
      key: '+92',
    },
    {
      label: 'Palau (+680)',
      text: '+680',
      value: 'PW',
      latitude: 7.5,
      longitude: 134.5,
      key: '+680',
    },
    {
      label: 'Palestinian Territory, Occupied (+970)',
      text: '+970',
      value: 'PS',
      latitude: 32,
      longitude: 35.25,
      key: '+970',
    },
    {
      label: 'Panama (+507)',
      text: '+507',
      value: 'PA',
      latitude: 9,
      longitude: -80,
      key: '+507',
    },
    {
      label: 'Papua New Guinea (+675)',
      text: '+675',
      value: 'PG',
      latitude: -6,
      longitude: 147,
      key: '+675',
    },
    {
      label: 'Paraguay (+595)',
      text: '+595',
      value: 'PY',
      latitude: -23,
      longitude: -58,
      key: '+595',
    },
    {
      label: 'Peru (+51)',
      text: '+51',
      value: 'PE',
      latitude: -10,
      longitude: -76,
      key: '+51',
    },
    {
      label: 'Philippines (+63)',
      text: '+63',
      value: 'PH',
      latitude: 13,
      longitude: 122,
      key: '+63',
    },
    {
      label: 'Pitcairn (+870)',
      text: '+870',
      value: 'PN',
      latitude: -24.7,
      longitude: -127.4,
      key: '+870',
    },
    {
      label: 'Poland (+48)',
      text: '+48',
      value: 'PL',
      latitude: 52,
      longitude: 20,
      key: '+48',
    },
    {
      label: 'Portugal (+351)',
      text: '+351',
      value: 'PT',
      latitude: 39.5,
      longitude: -8,
      key: '+351',
    },
    {
      label: 'Puerto Rico (+1 939)',
      text: '+1 939',
      value: 'PR',
      latitude: 18.25,
      longitude: -66.5,
      key: '+1 939',
    },
    {
      label: 'Qatar (+974)',
      text: '+974',
      value: 'QA',
      latitude: 25.5,
      longitude: 51.25,
      key: '+974',
    },
    {
      label: 'Réunion (+262)',
      text: '+262',
      value: 'RE',
      latitude: -21.1,
      longitude: 55.6,
      key: '+262',
    },
    {
      label: 'Romania (+40)',
      text: '+40',
      value: 'RO',
      latitude: 46,
      longitude: 25,
      key: '+40',
    },
    {
      label: 'Russia (+7)',
      text: '+7',
      value: 'RU',
      latitude: 60,
      longitude: 100,
      key: '+7',
    },
    {
      label: 'Rwanda (+250)',
      text: '+250',
      value: 'RW',
      latitude: -2,
      longitude: 30,
      key: '+250',
    },
    {
      label: 'Saint Helena, Ascension and Tristan Da Cunha (+290)',
      text: '+290',
      value: 'SH',
      latitude: -15.9333,
      longitude: -5.7,
      key: '+290',
    },
    {
      label: 'Saint Kitts and Nevis (+1 869)',
      text: '+1 869',
      value: 'KN',
      latitude: 17.3333,
      longitude: -62.75,
      key: '+1 869',
    },
    {
      label: 'Saint Lucia (+1 758)',
      text: '+1 758',
      value: 'LC',
      latitude: 13.8833,
      longitude: -61.1333,
      key: '+1 758',
    },
    {
      label: 'Saint Pierre and Miquelon (+508)',
      text: '+508',
      value: 'PM',
      latitude: 46.8333,
      longitude: -56.3333,
      key: '+508',
    },
    {
      label: 'Saint Vincent and the Grenadines (+1 784)',
      text: '+1 784',
      value: 'VC',
      latitude: 13.25,
      longitude: -61.2,
      key: '+1 784',
    },
    {
      label: 'Samoa (+685)',
      text: '+685',
      value: 'WS',
      latitude: -13.5833,
      longitude: -172.3333,
      key: '+685',
    },
    {
      label: 'San Marino (+378)',
      text: '+378',
      value: 'SM',
      latitude: 43.7667,
      longitude: 12.4167,
      key: '+378',
    },
    {
      label: 'Sao Tome and Principe (+239)',
      text: '+239',
      value: 'ST',
      latitude: 1,
      longitude: 7,
      key: '+239',
    },
    {
      label: 'Saudi Arabia (+966)',
      text: '+966',
      value: 'SA',
      latitude: 25,
      longitude: 45,
      key: '+966',
    },
    {
      label: 'Senegal (+221)',
      text: '+221',
      value: 'SN',
      latitude: 14,
      longitude: -14,
      key: '+221',
    },
    {
      label: 'Serbia (+381)',
      text: '+381',
      value: 'RS',
      latitude: 44,
      longitude: 21,
      key: '+381',
    },
    {
      label: 'Seychelles (+248)',
      text: '+248',
      value: 'SC',
      latitude: -4.5833,
      longitude: 55.6667,
      key: '+248',
    },
    {
      label: 'Sierra Leone (+232)',
      text: '+232',
      value: 'SL',
      latitude: 8.5,
      longitude: -11.5,
      key: '+232',
    },
    {
      label: 'Singapore (+65)',
      text: '+65',
      value: 'SG',
      latitude: 1.3667,
      longitude: 103.8,
      key: '+65',
    },
    {
      label: 'Slovakia (+421)',
      text: '+421',
      value: 'SK',
      latitude: 48.6667,
      longitude: 19.5,
      key: '+421',
    },
    {
      label: 'Slovenia (+386)',
      text: '+386',
      value: 'SI',
      latitude: 46,
      longitude: 15,
      key: '+386',
    },
    {
      label: 'Solomon Islands (+677)',
      text: '+677',
      value: 'SB',
      latitude: -8,
      longitude: 159,
      key: '+677',
    },
    {
      label: 'Somalia (+252)',
      text: '+252',
      value: 'SO',
      latitude: 10,
      longitude: 49,
      key: '+252',
    },
    {
      label: 'South Africa (+27)',
      text: '+27',
      value: 'ZA',
      latitude: -29,
      longitude: 24,
      key: '+27',
    },
    {
      label: 'South Georgia and the South Sandwich Islands (+500)',
      text: '+500',
      value: 'GS',
      latitude: -54.5,
      longitude: -37,
      key: '+500',
    },
    {
      label: 'Spain (+34)',
      text: '+34',
      value: 'ES',
      latitude: 40,
      longitude: -4,
      key: '+34',
    },
    {
      label: 'Sri Lanka (+94)',
      text: '+94',
      value: 'LK',
      latitude: 7,
      longitude: 81,
      key: '+94',
    },
    {
      label: 'Sudan (+249)',
      text: '+249',
      value: 'SD',
      latitude: 15,
      longitude: 30,
      key: '+249',
    },
    {
      label: 'Surilabel (+597)',
      text: '+597',
      value: 'SR',
      latitude: 4,
      longitude: -56,
      key: '+597',
    },
    {
      label: 'Svalbard and Jan Mayen (+47)',
      text: '+47',
      value: 'SJ',
      latitude: 78,
      longitude: 20,
      key: '+47',
    },
    {
      label: 'Swaziland (+268)',
      text: '+268',
      value: 'SZ',
      latitude: -26.5,
      longitude: 31.5,
      key: '+268',
    },
    {
      label: 'Sweden (+46)',
      text: '+46',
      value: 'SE',
      latitude: 62,
      longitude: 15,
      key: '+46',
    },
    {
      label: 'Switzerland (+41)',
      text: '+41',
      value: 'CH',
      latitude: 47,
      longitude: 8,
      key: '+41',
    },
    {
      label: 'Syrian Arab Republic (+963)',
      text: '+963',
      value: 'SY',
      latitude: 35,
      longitude: 38,
      key: '+963',
    },
    {
      label: 'Taiwan (+886)',
      text: '+886',
      value: 'TW',
      latitude: 23.5,
      longitude: 121,
      key: '+886',
    },
    {
      label: 'Tajikistan (+992)',
      text: '+992',
      value: 'TJ',
      latitude: 39,
      longitude: 71,
      key: '+992',
    },
    {
      label: 'Tanzania, United Republic of (+255)',
      text: '+255',
      value: 'TZ',
      latitude: -6,
      longitude: 35,
      key: '+255',
    },
    {
      label: 'Thailand (+66)',
      text: '+66',
      value: 'TH',
      latitude: 15,
      longitude: 100,
      key: '+66',
    },
    {
      label: 'Timor-Leste (+670)',
      text: '+670',
      value: 'TL',
      latitude: -8.55,
      longitude: 125.5167,
      key: '+670',
    },
    {
      label: 'Togo (+228)',
      text: '+228',
      value: 'TG',
      latitude: 8,
      longitude: 1.1667,
      key: '+228',
    },
    {
      label: 'Tokelau (+690)',
      text: '+690',
      value: 'TK',
      latitude: -9,
      longitude: -172,
      key: '+690',
    },
    {
      label: 'Tonga (+676)',
      text: '+676',
      value: 'TO',
      latitude: -20,
      longitude: -175,
      key: '+676',
    },
    {
      label: 'Trinidad and Tobago (+1 868)',
      text: '+1 868',
      value: 'TT',
      latitude: 11,
      longitude: -61,
      key: '+1 868',
    },
    {
      label: 'Tunisia (+216)',
      text: '+216',
      value: 'TN',
      latitude: 34,
      longitude: 9,
      key: '+216',
    },
    {
      label: 'Turvalue (+90)',
      text: '+90',
      value: 'TR',
      latitude: 39,
      longitude: 35,
      key: '+90',
    },
    {
      label: 'Turkmenistan (+993)',
      text: '+993',
      value: 'TM',
      latitude: 40,
      longitude: 60,
      key: '+993',
    },
    {
      label: 'Turks and Caicos Islands (+1 649)',
      text: '+1 649',
      value: 'TC',
      latitude: 21.75,
      longitude: -71.5833,
      key: '+1 649',
    },
    {
      label: 'Tuvalu (+688)',
      text: '+688',
      value: 'TV',
      latitude: -8,
      longitude: 178,
      key: '+688',
    },
    {
      label: 'Uganda (+256)',
      text: '+256',
      value: 'UG',
      latitude: 1,
      longitude: 32,
      key: '+256',
    },
    {
      label: 'Ukraine (+380)',
      text: '+380',
      value: 'UA',
      latitude: 49,
      longitude: 32,
      key: '+380',
    },
    {
      label: 'United Arab Emirates (+971)',
      text: '+971',
      value: 'AE',
      latitude: 24,
      longitude: 54,
      key: '+971',
    },
    {
      label: 'United Kingdom (+44)',
      text: '+44',
      value: 'GB',
      latitude: 54,
      longitude: -2,
      key: '+44',
    },
    {
      label: 'United States of America (+1)',
      text: '+1',
      value: 'US',
      latitude: 38,
      longitude: -97,
      key: '+1',
    },
    {
      label: 'United States Minor Outlying Islands (+1581)',
      text: '+1581',
      value: 'UM',
      latitude: 19.2833,
      longitude: 166.6,
      key: '+1581',
    },
    {
      label: 'Uruguay (+598)',
      text: '+598',
      value: 'UY',
      latitude: -33,
      longitude: -56,
      key: '+598',
    },
    {
      label: 'Uzbekistan (+998)',
      text: '+998',
      value: 'UZ',
      latitude: 41,
      longitude: 64,
      key: '+998',
    },
    {
      label: 'Vanuatu (+678)',
      text: '+678',
      value: 'VU',
      latitude: -16,
      longitude: 167,
      key: '+678',
    },
    {
      label: 'Venezuela, Bolivarian Republic of (+58)',
      text: '+58',
      value: 'VE',
      latitude: 8,
      longitude: -66,
      key: '+58',
    },
    {
      label: 'Viet Nam (+84)',
      text: '+84',
      value: 'VN',
      latitude: 16,
      longitude: 106,
      key: '+84',
    },
    {
      label: 'Virgin Islands, British (+1 284)',
      text: '+1 284',
      value: 'VG',
      latitude: 18.5,
      longitude: -64.5,
      key: '+1 284',
    },
    {
      label: 'Virgin Islands, U.S. (+1 340)',
      text: '+1 340',
      value: 'VI',
      latitude: 18.3333,
      longitude: -64.8333,
      key: '+1 340',
    },
    {
      label: 'Wallis and Futuna (+681)',
      text: '+681',
      value: 'WF',
      latitude: -13.3,
      longitude: -176.2,
      key: '+681',
    },
    {
      label: 'Western Sahara (+732)',
      text: '+732',
      value: 'EH',
      latitude: 24.5,
      longitude: -13,
      key: '+732',
    },
    {
      label: 'Yemen (+967)',
      text: '+967',
      value: 'YE',
      latitude: 15,
      longitude: 48,
      key: '+967',
    },
    {
      label: 'Zambia (+260)',
      text: '+260',
      value: 'ZM',
      latitude: -15,
      longitude: 30,
      key: '+260',
    },
    {
      label: 'Zimbabwe (+263)',
      text: '+263',
      value: 'ZW',
      latitude: -20,
      longitude: 30,
      key: '+263',
    },
  ];
  
  export default countrylabels;
  